@DevOpsApi_HostAddress = http://localhost:5141

GET {{DevOpsApi_HostAddress}}/work-item-dependency/
Accept: application/json

###

GET {{DevOpsApi_HostAddress}}/work-items/sprint/
Accept: application/json

###

GET {{DevOpsApi_HostAddress}}/authentication
Accept: application/json
Authorization: 

###